from libs.feature_store.features import vEight_testing, vSeven_testing2


EXPECTED_V7_FEATURES = [
    "age_dec_avg_diff",
    "age_ratio_diff",
    "reach_ratio_dec_avg_diff",
    "days_since_last_fight_dec_avg_diff",
    "days_since_last_fight_dec_avg",
    "weightclass_encoded",
    "sig_str_land_ratio_dec_adjperf_dec_avg_diff",
    "sig_str_def_dec_adjperf_dec_avg_diff",
    "sig_str_acc_dec_adjperf_dec_avg_diff",
    "head_land_ratio_dec_adjperf_dec_avg_diff",
    "head_def_dec_adjperf_dec_avg_diff",
    "head_per_sig_str_land_dec_avg_diff",
    "body_def_dec_adjperf_dec_avg_diff",
    "body_acc_dec_adjperf_dec_avg_diff",
    "leg_land_per_min_dec_adjperf_dec_avg_diff",
    "leg_def_dec_adjperf_dec_avg_diff",
    "distance_land_ratio_dec_adjperf_dec_avg_diff",
    "distance_land_rd1_ratio_dec_adjperf_dec_avg_diff",
    "distance_acc_dec_adjperf_dec_avg_diff",
    "distance_land_per_min_dec_adjperf_dec_avg_diff",
    "distance_per_sig_str_land_dec_avg_diff",
    "clinch_land_ratio_dec_adjperf_dec_avg_diff",
    "clinch_acc_dec_adjperf_dec_avg_diff",
    "ground_land_ratio_dec_adjperf_dec_avg_diff",
    "ground_land_per_ctrl_dec_avg_diff",
    "ko_per_sig_str_land_dec_adjperf_dec_avg_diff",
    "ko_ratio_dec_adjperf_dec_avg_diff",
    "sub_att_ratio_dec_adjperf_dec_avg_diff",
    "sub_att_dec_avg_diff",
    "sub_def_dec_adjperf_dec_avg_diff",
    "win_dec_adjperf_dec_avg_diff",
    "rev_per_ctrlopp_dec_adjperf_dec_avg_diff",
    "rev_per_ctrlopp_dec_avg_diff",
    "rev_ratio_dec_adjperf_dec_avg_diff",
    "ctrl_ratio_dec_adjperf_dec_avg_diff",
    "ctrl_per_min_opp_dec_avg_diff",
    "td_att_opp_dec_avg_diff",
    "td_att_rd1_opp_dec_avg_diff",
    "td_land_per_ctrl_dec_adjperf_dec_avg_diff",
    "td_per_sig_str_att_dec_adjperf_dec_avg_diff",
]

EXPECTED_V8_FEATURES = [
    "age_dec_avg_diff",
    "age_ratio_diff",
    "reach_ratio_dec_avg_diff",
    "days_since_last_fight_dec_avg_diff",
    "sig_str_land_per_min_dec_adjperf_dec_avg_diff",
    "weightclass_encoded",
    "sig_str_land_ratio_dec_adjperf_dec_avg_diff",
    "clinch_def_dec_adjperf_dec_avg_diff",
    "sig_str_acc_dec_adjperf_dec_avg_diff",
    "head_land_ratio_dec_adjperf_dec_avg_diff",
    "head_def_dec_adjperf_dec_avg_diff",
    "head_acc_dec_adjperf_dec_avg_diff",
    "body_def_dec_adjperf_dec_avg_diff",
    "body_acc_dec_adjperf_dec_avg_diff",
    "leg_land_per_min_dec_adjperf_dec_avg_diff",
    "leg_acc_dec_adjperf_dec_avg_diff",
    "distance_land_ratio_dec_adjperf_dec_avg_diff",
    "sig_str_land_pressure_dec_adjperf_dec_avg_diff",
    "distance_acc_dec_adjperf_dec_avg_diff",
    "distance_land_per_min_dec_adjperf_dec_avg_diff",
    "body_land_ratio_dec_adjperf_dec_avg_diff",
    "clinch_land_ratio_dec_adjperf_dec_avg_diff",
    "clinch_acc_dec_adjperf_dec_avg_diff",
    "ground_acc_dec_adjperf_dec_avg_diff",
    "ground_land_per_ctrl_dec_avg_diff",
    "ko_per_sig_str_land_dec_adjperf_dec_avg_diff",
    "ko_ratio_dec_adjperf_dec_avg_diff",
    "sub_att_ratio_dec_adjperf_dec_avg_diff",
    "sub_att_dec_avg_diff",
    "sub_def_dec_adjperf_dec_avg_diff",
    "win_dec_adjperf_dec_avg_diff",
    "rev_per_ctrlopp_dec_adjperf_dec_avg_diff",
    "td_acc_dec_adjperf_dec_avg_diff",
    "td_def_dec_adjperf_dec_avg_diff",
    "ctrl_ratio_dec_adjperf_dec_avg_diff",
    "ctrl_per_min_opp_dec_avg_diff",
    "td_att_opp_dec_avg_diff",
    "td_att_rd1_opp_dec_avg_diff",
    "td_land_per_ctrl_dec_adjperf_dec_avg_diff",
    "td_per_sig_str_att_dec_adjperf_dec_avg_diff",
]


def test_v7_and_v8_feature_portfolios_have_exact_ordered_identities():
    assert vSeven_testing2 == EXPECTED_V7_FEATURES
    assert len(vSeven_testing2) == len(set(vSeven_testing2)) == 40

    assert vEight_testing == EXPECTED_V8_FEATURES
    assert len(vEight_testing) == len(set(vEight_testing)) == 40
